# Generated by Django 5.2.7 on 2025-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='available_groups',
            field=models.ManyToManyField(blank=True, null=True, to='api.group'),
        ),
    ]
